apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        ports:
            - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db

      - name: mongo-api
        image: mike04/mongoslice:latest
        ports:
            - containerPort: 8083

      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongo-pvc
